defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:10.15-stretch-browsers-legacy

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install Angular
          command: sudo npm i @angular/cli -g > /dev/null
      - run:
          name: Install local dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Linting
          command: ng lint
      - run:
          name: Testing
          command: ng test --watch=false
      - run:
          name: Building
          command: ng build --prod
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
            - package.json
            - firebase.json
            - database.rules.json
            - .firebaserc

  deploy_develop:
    <<: *defaults
    steps:
      - run:
          name: Deploy Development Branch
          command: echo ${CIRCLE_BRANCH}

  deploy_master:
    <<: *defaults
    steps:
      - run:
          name: Deploy Master Branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install Firebase
          command: sudo npm i firebase-tools -g
      - run:
          name: Deploy Master to Firebase
          command: firebase deploy --token=$FIREBASE_TOKEN --debug

workflows:
  version: 2
  -deploy:
    jobs:
      - build
      - deploy_develop:
          requires:
            - build
          filters:
            branches:
              only: develop

      - deploy_master:
          requires:
            - build
          filters:
            branches:
              only: master
