name: CI - build,test affected projects on Pr+Merge
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # needed for all cases
      - if: github.event_name == 'push' && github.ref_name == 'main'
        uses: actions/checkout@v3
      # needed for nx affected command
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # needed for nx affected command
      - if: github.event_name == 'pull_request'
        run: git fetch --no-tags --depth=1 origin $BASE_BRANCH

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install dependencies
        run: npm ci

      # TODO: have different dist locations to un in parallel
      - name: Run Nx Affected lint,test
        run: npx nx affected --targets=lint,test
      - name: Run Nx Affected build
        run: npx nx affected --targets=build
      - name: Run Nx Affected prerende
        run: npx nx affected --targets=prerende
