name: E2E Cloudflare Pages Preview Channel on PR
on:

jobs:
  build_and_cloudflare_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Production build for static file hosting (client only)
        run: npm run nx run cloudflare-worker:user-flow:production -- --format=md

      # use preview deployment
      - name: Test cloudflare preview pages hosting
        id: cloudflare-preview-pages-hosting
        uses: push-based/user-flow-gh-action@v0.4.1
        with:
          verbose: on
          commentId: cloudflare-preview-pages-hosting
          onlyComments: on
          outPath: ./dist/user-flow/cloudflare-worker
