name: E2E Firebase Preview Channel Hosting on PR
'on': pull_request
jobs:
  build_and_firebase_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Production build for static file hosting (client + prerender)
        run: npm run nx prerender ng-universal-express

      - name: Deploy firebase preview channel hosting
        id: previewDeployStep
        uses: FirebaseExtended/action-hosting-deploy@v0.7.1
        with:
          entryPoint: firebase.hosting.json
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANGULAR_MOVIES_A12D3 }}
          projectId: angular-movies-a12d3
          channelId: ${{ github.head_ref }}
          expires: 30d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: User Flow
        run: npm run nx run movies:user-flow:production -- --format=md --url=${{ fromJson(steps.previewDeployStep.outputs.urls)[0] }}

      - name: Test firebase preview channel hosting
        id: firebase-preview-channel-hosting
        uses: push-based/user-flow-gh-action@v0.4.1
        with:
          verbose: on
          commentId: firebase-preview-channel-hosting
          onlyComments: on
          outPath: ./dist/user-flow/movies
          rcPath: ./projects/movies/.user-flowrc.json

